[package]
name = "picoaide-dsh-store"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
picoaide-dsh-util = { path = "../dsh-util" }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true }
url = "2"
rand = { workspace = true }
sha2 = "0.10"
hex = "0.4"
