// Code generated by picoaide-wasm-imports-gen; DO NOT EDIT.
//
// 重跑（改任一来源程序、或升级 Go 工具链后**必须**重跑）：
//
//	cd server && go run ./cmd/picoaide-wasm-imports-gen
//
// 比对模式（门禁，不一致即非零退出）：
//
//	cd server && go run ./cmd/picoaide-wasm-imports-gen -check
//
// 判据 = 符号 + 类型（§4.2）。数据来源 = 下列参考程序真编译产物（GOOS=wasip1 GOARCH=wasm）
// 导入段的**并集** —— 手写清单即门禁测试红（§5.5「导入面生成」）。
//   - ./internal/wasmapp/refapp              原始  18 条 / 去重  16 条
//   - ./internal/wasmapp/refapp/wasiprobe    原始  35 条 / 去重  30 条
//   - ./internal/wasmapp/refapp/stdprobe     原始  35 条 / 去重  31 条
//
// ⚠️ 白名单的语义 = **Go wasip1 运行时可能发出的全部 wasi_snapshot_preview1 导入**
// （保守超集），不是「参考实现恰好用到的那些」：只按最小样例生成会让任何用了一行 os.Stat
// 的合法 Go 应用被判 IMPORT_NOT_ALLOWED（模块 C 实测缺陷）；同理，[P0-1/2026-09-18] 实测
// html/text template 的 **Execute（渲染）** 会带出 sock_accept / sock_shutdown、
// (*os.File).ReadAt/WriteAt 会带出 fd_pread / fd_pwrite —— 缺这四条时「用 html/template
// 渲染页面的合法应用」根本发不出去（本平台最主要的用法，§4.2 R8）。
// 为什么允许 path_open / fd_readdir / fd_pread 等并不违反红线：
//   - 红线 5（不能读宿主文件）由**运行时零 preopen** 保证（§4.3 / §15.1 第 1 条）：没有任何
//     preopen 时文件操作一律 DENIED，errno 视调用层与路径形态为 EBADF(8) / EPERM(63) /
//     ENOTDIR(54) —— **不是 ENOSYS**（审计实测 errno 矩阵，2026-09-18 更正），guest 拿不到可用 fd；
//   - 红线 4（不能出站）由「**没有任何途径得到一个 socket fd**」保证：preview1 只有
//     sock_accept / sock_recv / sock_send / sock_shutdown，**没有** sock_open / sock_bind /
//     sock_listen / sock_connect ⇒ 自造不出 socket fd（实测 sock_accept(0..10) 与
//     sock_shutdown(3) 全 EBADF(8)，syscall.Socket 在 wasip1 上不可用）。所以白名单要拒的是
//     **造 fd 的那几个 sock_* 符号**与非 wasi_snapshot_preview1 的模块（imports_gen_test.go
//     有反向断言），而不是把 Go 运行时会发出的 sock_accept / sock_shutdown 一并拒掉。
//
// ⚠️ 这里列的是 **WASI 导入**，不是宿主能力：宿主能力（db.* / ai.chat / log / assets.read 等）
// 走 stdin/stdout 上的 JSON-RPC（§7.2），根本不经过 wasm 导入段；其中 **fd_read** 是 ABI 读
// stdin 请求帧的硬要求（§4.2）。
//
// 签名格式：形参类型短名串 + "_" + 结果类型短名串（i32/i64/f32/f64/v128/funcref/externref；例：fd_write(i32,i32,i32,i32)->i32 = "i32i32i32i32_i32"；无结果如 "i32_"；无参无结果 "_"）
//
// 本次生成：并集 34 条 (module, name, kind, signature)。

package wasmmod

// ImportWhitelist 是导入面白名单（生成产物，勿手改；判据 = 符号 + 类型，§4.2）。
var ImportWhitelist = []ImportSpec{
	{Module: "wasi_snapshot_preview1", Name: "args_get", Kind: KindFunc, Signature: "i32i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "args_sizes_get", Kind: KindFunc, Signature: "i32i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "clock_time_get", Kind: KindFunc, Signature: "i32i64i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "environ_get", Kind: KindFunc, Signature: "i32i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "environ_sizes_get", Kind: KindFunc, Signature: "i32i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "fd_close", Kind: KindFunc, Signature: "i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "fd_fdstat_get", Kind: KindFunc, Signature: "i32i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "fd_fdstat_set_flags", Kind: KindFunc, Signature: "i32i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "fd_filestat_get", Kind: KindFunc, Signature: "i32i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "fd_filestat_set_size", Kind: KindFunc, Signature: "i32i64_i32"},
	{Module: "wasi_snapshot_preview1", Name: "fd_pread", Kind: KindFunc, Signature: "i32i32i32i64i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "fd_prestat_dir_name", Kind: KindFunc, Signature: "i32i32i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "fd_prestat_get", Kind: KindFunc, Signature: "i32i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "fd_pwrite", Kind: KindFunc, Signature: "i32i32i32i64i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "fd_read", Kind: KindFunc, Signature: "i32i32i32i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "fd_readdir", Kind: KindFunc, Signature: "i32i32i32i64i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "fd_seek", Kind: KindFunc, Signature: "i32i64i32i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "fd_sync", Kind: KindFunc, Signature: "i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "fd_write", Kind: KindFunc, Signature: "i32i32i32i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "path_create_directory", Kind: KindFunc, Signature: "i32i32i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "path_filestat_get", Kind: KindFunc, Signature: "i32i32i32i32i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "path_filestat_set_times", Kind: KindFunc, Signature: "i32i32i32i32i64i64i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "path_open", Kind: KindFunc, Signature: "i32i32i32i32i32i64i64i32i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "path_readlink", Kind: KindFunc, Signature: "i32i32i32i32i32i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "path_remove_directory", Kind: KindFunc, Signature: "i32i32i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "path_rename", Kind: KindFunc, Signature: "i32i32i32i32i32i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "path_symlink", Kind: KindFunc, Signature: "i32i32i32i32i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "path_unlink_file", Kind: KindFunc, Signature: "i32i32i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "poll_oneoff", Kind: KindFunc, Signature: "i32i32i32i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "proc_exit", Kind: KindFunc, Signature: "i32_"},
	{Module: "wasi_snapshot_preview1", Name: "random_get", Kind: KindFunc, Signature: "i32i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "sched_yield", Kind: KindFunc, Signature: "_i32"},
	{Module: "wasi_snapshot_preview1", Name: "sock_accept", Kind: KindFunc, Signature: "i32i32i32_i32"},
	{Module: "wasi_snapshot_preview1", Name: "sock_shutdown", Kind: KindFunc, Signature: "i32i32_i32"},
}
