[package]
name = "picoaide-dsh-server"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
picoaide-dsh-store = { path = "../dsh-store" }
axum = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
serde_yaml = "0.9.34"
zip = "8"
flate2 = "1"
tar = "0.4"
sha2 = "0.10"
hex = "0.4"
base64 = { workspace = true }
