/**
 * Inline styles for the cron plugin surfaces (local repository convention:
 * no CSS-Modules build pipeline in this workspace, see dsh-connectors).
 * Tokens follow the DSH design-token vocabulary with neutral fallbacks so
 * the surfaces render on any theme.
 */
import type { CSSProperties } from 'react'

export const styles: Record<string, CSSProperties> = {
  cron: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    minWidth: 280,
    fontSize: 13,
    color: 'var(--dsw-text, #d5d7e0)',
    background: 'transparent',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 12px',
    borderBottom: '1px solid var(--dsw-border, rgba(128,128,128,0.25))',
  },
  title: {
    flex: 1,
    margin: 0,
    fontSize: 13,
    fontWeight: 600,
  },
  meta: { fontSize: 11, opacity: 0.65, whiteSpace: 'nowrap' },
  list: {
    flex: 1,
    overflowY: 'auto',
    padding: 8,
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  empty: { padding: '24px 12px', textAlign: 'center', opacity: 0.6 },
  job: {
    border: '1px solid var(--dsw-border, rgba(128,128,128,0.25))',
    borderRadius: 8,
    padding: '8px 10px',
    background: 'var(--dsw-surface, rgba(30,32,42,0.85))',
  },
  jobRow: { display: 'flex', alignItems: 'center', gap: 8 },
  jobName: {
    flex: 1,
    fontWeight: 600,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  jobCron: { fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace', fontSize: 11, opacity: 0.8 },
  jobNext: { fontSize: 11, opacity: 0.65 },
  actions: { display: 'flex', gap: 4, alignItems: 'center' },
  button: {
    border: '1px solid var(--dsw-border, rgba(128,128,128,0.3))',
    borderRadius: 6,
    background: 'transparent',
    color: 'inherit',
    fontSize: 12,
    padding: '3px 8px',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  buttonHover: {},
  buttonDisabled: { opacity: 0.45, cursor: 'default' },
  buttonPrimary: { borderColor: 'var(--dsw-accent, #4d6bfe)', color: 'var(--dsw-accent, #4d6bfe)' },
  switch: { display: 'inline-flex', alignItems: 'center', gap: 6, fontSize: 12, cursor: 'pointer' },
  history: {
    marginTop: 6,
    paddingTop: 6,
    borderTop: '1px dashed var(--dsw-border, rgba(128,128,128,0.2))',
    fontSize: 11,
    opacity: 0.75,
  },
  historyRow: { display: 'flex', gap: 8, padding: '1px 0' },
  historyTime: { opacity: 0.7 },
  resultOk: { color: 'var(--dsw-success, #4caf7d)' },
  resultFail: { color: 'var(--dsw-danger, #e06666)' },
  resultCancel: { opacity: 0.7 },
  resultPending: { color: 'var(--dsw-warning, #d9a441)' },
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.45)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2147483000,
  },
  editor: {
    width: 'min(480px, 92vw)',
    maxHeight: '86vh',
    overflowY: 'auto',
    border: '1px solid var(--dsw-border, rgba(128,128,128,0.35))',
    borderRadius: 10,
    background: 'var(--dsw-surface, #1e202a)',
    padding: '14px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    color: 'var(--dsw-text, #d5d7e0)',
    fontSize: 13,
  },
  field: { display: 'flex', flexDirection: 'column', gap: 4 },
  label: { fontSize: 12, opacity: 0.8 },
  input: {
    border: '1px solid var(--dsw-border, rgba(128,128,128,0.35))',
    borderRadius: 6,
    background: 'var(--dsw-input, rgba(0,0,0,0.25))',
    color: 'inherit',
    fontSize: 13,
    padding: '5px 8px',
    fontFamily: 'inherit',
  },
  presets: { display: 'flex', flexWrap: 'wrap', gap: 6 },
  preset: {
    fontSize: 11,
    padding: '2px 8px',
    borderRadius: 999,
    border: '1px solid var(--dsw-border, rgba(128,128,128,0.3))',
    background: 'transparent',
    color: 'inherit',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  error: { color: 'var(--dsw-danger, #e06666)', fontSize: 12 },
  editorActions: { display: 'flex', justifyContent: 'flex-end', gap: 8, marginTop: 4 },
  card: { display: 'flex', flexDirection: 'column', gap: 10, fontSize: 13 },
  row: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  rowDesc: { fontSize: 12, opacity: 0.7 },
}
