/**
 * Inline styles for the task board surfaces (local repository convention:
 * no CSS-Modules build pipeline; see dsh-connectors / dsh-cron). Tokens
 * follow the DSH design-token vocabulary with neutral fallbacks.
 */
import type { CSSProperties } from 'react'

export const styles: Record<string, CSSProperties> = {
  board: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    minWidth: 640,
    // Positioning ancestor for the absolutely-positioned detail panel:
    // without this the panel anchored to the window frame instead of the
    // board container (P2-5).
    position: 'relative',
    fontSize: 13,
    color: 'var(--dsw-alias-label-primary)',
    background: 'transparent',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '10px 14px',
    borderBottom: '1px solid var(--dsw-alias-border-l2)',
    // P0-4: under a narrow window the header could flex-shrink to zero and
    // collapse the back-to-chat button; keep the row at its content height.
    flexShrink: 0,
    minHeight: 44,
  },
  title: { flex: 1, margin: 0, fontSize: 14, fontWeight: 600 },
  meta: { fontSize: 11, opacity: 0.65, whiteSpace: 'nowrap' },
  search: {
    border: '1px solid var(--dsw-alias-border-l3)',
    borderRadius: 6,
    background: 'var(--dsw-alias-bg-layer-3)',
    color: 'inherit',
    fontSize: 12,
    padding: '4px 8px',
    fontFamily: 'inherit',
    width: 160,
  },
  button: {
    border: '1px solid var(--dsw-alias-border-l2)',
    borderRadius: 6,
    background: 'transparent',
    color: 'inherit',
    fontSize: 12,
    padding: '4px 10px',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  buttonPrimary: { borderColor: 'var(--dsw-alias-state-business-primary)', color: 'var(--dsw-alias-state-business-primary)' },
  buttonDisabled: { opacity: 0.45, cursor: 'default' },
  error: { color: 'var(--dsw-alias-state-error-primary)', fontSize: 12, padding: '4px 14px' },
  columns: {
    flex: 1,
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(180px, 1fr))',
    gap: 10,
    padding: '10px 14px',
    overflowX: 'auto',
    overflowY: 'hidden',
    alignItems: 'start',
  },
  column: {
    display: 'flex',
    flexDirection: 'column',
    maxHeight: '100%',
    border: '1px solid var(--dsw-alias-border-l1)',
    borderRadius: 10,
    background: 'var(--dsw-alias-bg-layer-2)',
  },
  columnHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '8px 10px',
    borderBottom: '1px solid var(--dsw-alias-border-l1)',
  },
  columnTitle: { flex: 1, margin: 0, fontSize: 12, fontWeight: 600 },
  columnCount: {
    fontSize: 11,
    opacity: 0.7,
    background: 'var(--dsw-alias-border-l1)',
    borderRadius: 999,
    padding: '1px 7px',
  },
  statusDot: { width: 8, height: 8, borderRadius: '50%', display: 'inline-block' },
  cards: {
    flex: 1,
    overflowY: 'auto',
    padding: 8,
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  card: {
    border: '1px solid var(--dsw-alias-border-l2)',
    borderRadius: 8,
    padding: '8px 10px',
    background: 'var(--dsw-alias-bg-layer-2)',
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  cardTitle: { fontWeight: 600, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  cardDesc: {
    fontSize: 11,
    opacity: 0.7,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  cardMeta: { fontSize: 10, opacity: 0.55, display: 'flex', gap: 6 },
  columnEmpty: { padding: '20px 8px', textAlign: 'center', opacity: 0.5, fontSize: 12 },
  detail: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 'min(420px, 40vw)',
    borderLeft: '1px solid var(--dsw-alias-border-l2)',
    background: 'var(--dsw-alias-bg-layer-2)',
    display: 'flex',
    flexDirection: 'column',
    zIndex: 10,
  },
  detailHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 12px',
    borderBottom: '1px solid var(--dsw-alias-border-l2)',
  },
  detailBody: { flex: 1, overflowY: 'auto', padding: '10px 12px', display: 'flex', flexDirection: 'column', gap: 10 },
  field: { display: 'flex', flexDirection: 'column', gap: 4 },
  label: { fontSize: 11, opacity: 0.75 },
  value: { fontSize: 13, whiteSpace: 'pre-wrap' },
  input: {
    border: '1px solid var(--dsw-alias-border-l3)',
    borderRadius: 6,
    background: 'var(--dsw-alias-bg-layer-3)',
    color: 'inherit',
    fontSize: 13,
    padding: '5px 8px',
    fontFamily: 'inherit',
  },
  history: { display: 'flex', flexDirection: 'column', gap: 4, fontSize: 12 },
  historyRow: { display: 'flex', gap: 8, alignItems: 'center' },
  switch: { display: 'inline-flex', alignItems: 'center', gap: 6, fontSize: 12, cursor: 'pointer' },
  row: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  rowDesc: { fontSize: 12, opacity: 0.7 },
  resultOk: { color: 'var(--dsw-alias-state-success-primary)' },
  resultFail: { color: 'var(--dsw-alias-state-error-primary)' },
  resultCancel: { opacity: 0.7 },
  resultPending: { color: 'var(--dsw-alias-state-warn-primary)' },
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'var(--dsw-alias-bg-mask-1)',
    backdropFilter: 'var(--dsw-mask-blur)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2147483000,
  },
  editor: {
    width: 'min(520px, 92vw)',
    maxHeight: '88vh',
    overflowY: 'auto',
    border: '1px solid var(--dsw-alias-border-l3)',
    borderRadius: 12,
    background: 'var(--dsw-alias-bg-layer-2)',
    boxShadow: 'var(--dsw-shadow-lv3)',
    padding: '14px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    color: 'var(--dsw-alias-label-primary)',
    fontSize: 13,
  },
  editorActions: { display: 'flex', justifyContent: 'flex-end', gap: 8, marginTop: 4 },
  schedule: {
    border: '1px dashed var(--dsw-alias-border-l2)',
    borderRadius: 8,
    padding: '8px 10px',
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    fontSize: 12,
  },
}
