[package]
name = "picoaide-dsh-auth"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
picoaide-dsh-util = { path = "../dsh-util" }
picoaide-dsh-store = { path = "../dsh-store" }
axum = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true }
base64 = "0.22"
rand = "0.8"
hmac = "0.12"
sha2 = "0.10"
hex = "0.4"
ldap3 = "0.11"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
rsa = "0.9"
url = "2"
subtle = { workspace = true }
async-trait = "0.1"
